name: Docker Build, Push, and Scan

on:
  push:
    branches:
      - main  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: gorje6/dolibarr:latest  # Replace with your Docker Hub username and image name
          
      - name: Scan the Docker image for vulnerabilities
        uses: anchore/scan-action@v2
        with:
          image: "gorje6/dolibarr:latest"  # Replace with your Docker Hub username and image name
          fail-build: true
          severity-cutoff: 'high'
